### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by Toni500github** [reiryuki/One-UI-Home-Magisk-Module#2]
I have tried to zip it in .7z, .zip and .tar but nothing worked ![Screenshot_20220328-103632.png](https://user-images.githubusercontent.com/88878648/160359592-44423b7e-9395-45c7-be52-558c17acce3c.png)![Screenshot_20220328-103629.png](https://user-images.githubusercontent.com/88878648/160359608-3d3e8c2f-a7d4-470e-af6f-3690219e7645.png)![Screenshot_20220328-103557.png](https://user-images.githubusercontent.com/88878648/160359625-359c3558-5118-4bcf-99e5-439299d3dc6d.png)

**Comment by reiryuki** [comment]
Sorry I don't understand what you gonna do
This is a Magisk module, not a Magisk itself..

**Comment by Toni500github** [comment]
Oh, then what u should I do? Sorry it's my 1st time with magisk 😅
