### ISSUE TITLE
Doesn't work in J2 Core

### ISSUE THREAD

**Issue by WinG4merBR** [reiryuki/One-UI-Home-Magisk-Module#4]
The launcher doesn't work in Galaxy J2 Core, can I fix that? Or my phone is incompatible?

Phone info:
Samsung Galaxy J2 Core SM-J260M
j2corelte
Android 8.1 Go

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module X
3) Full logcat X
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.

Will be re-opened after you send the required files.
