### ISSUE TITLE
Support for folding devices

### ISSUE THREAD

**Issue by sorgelig** [reiryuki/One-UI-Home-Magisk-Module#5]
On Samsung Galaxy Fold 2, OneUI Home supports separate home configs, so i may have 2 separate widgets/icons sets for outer and inner screens.
I've tried your module on Xiaomi Fold 3 (Android 13). OneUI Home works but both displays show the same home screen. Is it possible to make them display separate configs?

**Comment by reiryuki** [comment]
Please move to discussions tab for any questions
